# Site settings
title: Kevin Mattheus Moerman
description: "Research Scientist, MIT Media Lab"
url: "https://kevinmoerman.org"

# Secondary Parameters
baseurl: ""
header-img: img/home-bg.jpg
headercolor: "#FFFFFF"
logo: /img/logos/KevinMoerman.png

# Tertiary Parameters
github_username: Kevin-Mattheus-Moerman
googlescholar_url: https://scholar.google.com/citations?user=0Bt1yzgAAAAJ&hl=en
twitter_username: KMMoerman
orcid_id: 0000-0003-3768-4269
impactstory_id: u/0000-0003-3768-4269
linkedin_username: kevin-moerman-98923831
email_address: kmoerman@mit.edu
#g-analytics: UA-75881392-1
altmetric: true

# Build settings
plugins: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["node_modules","README.md"]

# Jekyll Settings
defaults:
  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/home-bg.jpg"
  - scope:
      path: "img/gallery"
    values:
      image: true
